// Real time portfolio loader. Reads portfolio.json, hydrates the static shell.
(async function () {
  const $ = (sel) => document.querySelector(sel);
  const create = (tag, cls, html) => {
    const el = document.createElement(tag);
    if (cls) el.className = cls;
    if (html != null) el.innerHTML = html;
    return el;
  };

  function timeAgo(iso) {
    if (!iso) return "never";
    const then = new Date(iso).getTime();
    if (!Number.isFinite(then)) return "unknown";
    const seconds = Math.floor((Date.now() - then) / 1000);
    if (seconds < 60) return seconds + "s ago";
    const mins = Math.floor(seconds / 60);
    if (mins < 60) return mins + "m ago";
    const hours = Math.floor(mins / 60);
    if (hours < 24) return hours + "h ago";
    const days = Math.floor(hours / 24);
    return days + "d ago";
  }

  function setSyncStatus(iso) {
    const text = "last synced " + timeAgo(iso);
    $("#sync-text").textContent = text;
    $("#footer-sync").textContent = text + ", regenerated by launchd cron";
  }

  function hydrateHero(data) {
    const o = data.owner;
    $("#hero-tag").textContent = o.summary;

    const stats = [
      { num: data.counters.agents, label: "Agents" },
      { num: data.counters.brain_regions_wired, label: "Brain regions" },
      { num: data.counters.citadel_ramparts_live + "/" + data.counters.citadel_ramparts_total, label: "CITADEL live" },
      { num: data.counters.shipped_systems, label: "Featured systems" },
    ];
    const ul = $("#hero-stats");
    ul.innerHTML = "";
    stats.forEach((s) => {
      const li = create("li");
      li.appendChild(create("span", "stat-num", s.num));
      li.appendChild(create("span", "stat-label", s.label));
      ul.appendChild(li);
    });

    const ascii = $("#ascii-block");
    ascii.textContent = [
      "ARWIN BAGASLAO",
      "AI ENGINEER, BUILDS MULTI AGENT SYSTEMS IN PRODUCTION",
      "",
      "[ STATUS ]  online",
      "[ ROLE   ]  founder, CFO, AI engineer",
      "[ STACK  ]  python, apps script, MCP, streamlit, claude SDK",
      "[ AGENTS ]  " + data.counters.agents + " specialized",
      "[ BRAIN  ]  " + data.counters.brain_regions_wired + " wired, " + data.counters.brain_seats_empty + " reserved",
      "[ CITADEL]  " + data.counters.citadel_ramparts_live + "/" + data.counters.citadel_ramparts_total + " ramparts live",
    ].join("\n");
  }

  function hydrateHeadliners(list) {
    const ol = $("#headliners");
    ol.innerHTML = "";
    list.forEach((line) => {
      ol.appendChild(create("li", "", escape(line)));
    });
  }

  function escape(s) {
    return String(s).replace(/[&<>"']/g, (c) => ({
      "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;",
    }[c]));
  }

  function hydrateSystems(list) {
    const wrap = $("#systems-grid");
    wrap.innerHTML = "";
    list.forEach((s) => {
      const card = create("article", "system-card");
      card.appendChild(create("h3", "system-title", escape(s.title)));
      card.appendChild(create("p", "system-tagline", escape(s.tagline)));
      const meta = create("div", "system-meta");
      meta.appendChild(create("span", "chip", escape(s.stack)));
      meta.appendChild(create("span", "chip chip-ship", "ship: " + escape(s.ship)));
      card.appendChild(meta);
      if (s.metrics && s.metrics.length) {
        const ul = create("ul", "system-metrics");
        s.metrics.forEach((m) => ul.appendChild(create("li", "", escape(m))));
        card.appendChild(ul);
      }
      wrap.appendChild(card);
    });
  }

  function hydrateCitadel(list) {
    const wrap = $("#citadel-grid");
    wrap.innerHTML = "";
    list.forEach((r) => {
      const card = create("div", "rampart");
      const head = create("div", "rampart-head");
      head.appendChild(create("span", "rampart-name", escape(r.name)));
      head.appendChild(create("span", "rampart-phase", "P" + escape(r.phase)));
      card.appendChild(head);
      card.appendChild(create("p", "rampart-desc", escape(r.desc)));
      card.appendChild(create("span", "status status-" + r.status, escape(r.status)));
      wrap.appendChild(card);
    });
  }

  function hydrateBrain(regions, seats) {
    const wrap = $("#brain-grid");
    wrap.innerHTML = "";
    regions.forEach((r) => {
      const card = create("div", "brain-card");
      card.appendChild(create("div", "brain-region", escape(r.region)));
      card.appendChild(create("div", "brain-role", escape(r.role)));
      if (r.agents && r.agents.length) {
        const a = create("div", "brain-agents");
        r.agents.forEach((name) => a.appendChild(create("span", "brain-agent-chip", escape(name))));
        card.appendChild(a);
      }
      if (r.notes) card.appendChild(create("div", "brain-notes", escape(r.notes)));
      wrap.appendChild(card);
    });
    const seatWrap = $("#seats-grid");
    seatWrap.innerHTML = "";
    seats.forEach((s) => {
      const card = create("div", "seat-card");
      card.appendChild(create("div", "seat-name", "RESERVED, " + escape(s.name)));
      card.appendChild(create("div", "seat-role", escape(s.role)));
      card.appendChild(create("div", "seat-purpose", escape(s.purpose)));
      seatWrap.appendChild(card);
    });
  }

  function hydrateAgents(list) {
    const wrap = $("#agent-list");
    const sub = $("#agent-sub");
    sub.innerHTML = "Live count, " + list.length + " agent files in <code>~/.claude/agents/</code>";
    const render = (items) => {
      wrap.innerHTML = "";
      items.forEach((a) => {
        const row = create("div", "agent-row");
        row.appendChild(create("div", "agent-name", escape(a.name)));
        if (a.description) row.appendChild(create("div", "agent-desc", escape(a.description)));
        wrap.appendChild(row);
      });
    };
    render(list);
    const search = $("#agent-search");
    search.addEventListener("input", (e) => {
      const q = e.target.value.trim().toLowerCase();
      if (!q) return render(list);
      render(list.filter((a) =>
        a.name.toLowerCase().includes(q) ||
        (a.description || "").toLowerCase().includes(q)
      ));
    });
  }

  function hydrateStack(list) {
    const wrap = $("#stack-grid");
    wrap.innerHTML = "";
    list.forEach((t) => {
      const chip = create("span", "stack-chip", escape(t.label));
      chip.setAttribute("data-kind", t.kind);
      wrap.appendChild(chip);
    });
  }

  function showError(msg) {
    $("#hero-tag").textContent = msg;
    $("#sync-text").textContent = "sync error";
  }

  try {
    const url = "portfolio.json?t=" + Date.now();
    const res = await fetch(url);
    if (!res.ok) throw new Error("portfolio.json failed, " + res.status);
    const data = await res.json();

    setSyncStatus(data.meta.last_synced_utc);
    hydrateHero(data);
    hydrateHeadliners(data.headliners);
    hydrateSystems(data.shipped_systems);
    hydrateCitadel(data.citadel_ramparts);
    hydrateBrain(data.brain_regions, data.empty_seats);
    hydrateAgents(data.agents);
    hydrateStack(data.tech_stack);

    setInterval(() => setSyncStatus(data.meta.last_synced_utc), 30 * 1000);
  } catch (err) {
    console.error(err);
    showError("Failed to load portfolio data. Run sync.py to generate portfolio.json.");
  }
})();
